# Site settings
title: Slowenien
client:
  name: Slowenien
  link: "https://www.slovenia.info/de"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Grünes Licht für Slowenien: das kleine Land zwischen Adria und Alpen ist eines der sichersten und nachhaltigsten Länder der Welt.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/2020/slowenien" # the subpath of your site, e.g. /blog/
img:     "/de/2020/slowenien/_assets/img"
css:     "/de/2020/slowenien/_assets/css"
js:      "/de/2020/slowenien/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
